### ISSUE TITLE
[Question]セッション情報について

### ISSUE THREAD

**Issue by shinriyo** [chaingng/shoeisha_serverless_python_tutorial#3]
P146「セッション情報はローカルにほぞんしていましたが」とありますが、
`Session(app)` する前は、特に設定がなかったかと思います。
明示がないときはFlaskのデフォルトの動作としてメモリ上またはSQLiteかブラウザのLocalStorageか何かに保存されていたということでしょうか？

**Comment by vlayusuke** [comment]
本縁とは直接関係ないのかもしれませんが、

`python3 server.py`

を実行して動作確認を試みたときに、

`RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.`

というRuntimeエラーが出力されてローカルでの動作確認ができません。

原因として考えられるのは、views/views.pyの中で

`from flask import request, redirect, url_for, render_template, flash, session`

と明示的にsessionをimportしているところが関係あるのかなと思い、一旦import対象から外したのですが、やはり同じようなRuntimeErrorが発生して動作確認できない状況です。

もし回避方法をご存知の方がいらっしゃったらご教示いただけると大変ありがたいです。初歩的な質問で申し訳ありません。

**Comment by chaingng** [comment]
@shinriyo 
コメントありがとうございます。
前章のログイン機能の導入のところですが、
前提としてログイン機能の実現にはセッションが必要となりますため
Flask-loginが内部的にFlaskのsession機構を利用しております。

明示はされてなかったため、ご指摘のとおり理解しにくい部分があったかと思いますので
Q&Aに追記させていただくようにいたします。

@vlayusuke 
頂いたご質問につきまして、#10 を作成いただきありがとうございます。
そちらにて回答させていただいております。

**Comment by chaingng** [comment]
こちらのQ&Aに記載させていただきましたので、closeさせていただきます。

https://github.com/chaingng/shoeisha_serverless_python_tutorial#6-p146%E3%81%A7%E3%81%93%E3%82%8C%E3%81%BE%E3%81%A7%E3%82%BB%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3%E6%83%85%E5%A0%B1%E3%81%AF%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E3%81%AB%E4%BF%9D%E5%AD%98%E3%81%97%E3%81%A6%E3%81%84%E3%81%BE%E3%81%97%E3%81%9F%E3%81%8C%E3%81%A8%E3%81%82%E3%82%8B%E3%82%82%E3%81%AE%E3%81%AE%E3%81%93%E3%82%8C%E3%81%BE%E3%81%A7%E3%82%BB%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AE%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AF%E5%87%BA%E3%81%A6%E3%81%8D%E3%81%A6%E3%81%84%E3%81%AA%E3%81%84%E3%81%9F%E3%82%81%E3%81%A9%E3%81%AE%E7%AE%87%E6%89%80%E3%81%A7%E5%88%A9%E7%94%A8%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E3%81%AE%E3%81%8B
